services:
  php:
    image: php:fpm
    container_name: php
    volumes:
      - /var/www/html:/var/www/html
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    command: >
      /bin/sh -c "
      apt-get update &&
      apt-get install -y wget &&
      mkdir -p /var/www/html &&
      if [ ! -f /var/www/html/index.php ]; then
        wget -qO /var/www/html/index.php https://raw.githubusercontent.com/skippybossx/Super-Simple-File-Browser/refs/heads/main/ssfb.php;
      fi &&
      mkdir -p /etc/nginx/conf.d &&
      echo 'server {
        listen 80;
        server_name _;
        root /var/www/html;
        index index.php index.html;
        location / {
          try_files $$uri $$uri/ /index.php;
        }
        location ~ \\.php$$ {
          include fastcgi_params;
          fastcgi_pass php:9000;
          fastcgi_param SCRIPT_FILENAME $$document_root$$fastcgi_script_name;
        }
      }' > /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'
      "
    volumes:
      - /var/www/html:/var/www/html
    restart: unless-stopped
